//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPSAdvisingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseCourse
    {
        public BaseCourse()
        {
            this.Courses = new HashSet<Course>();
            this.Prerequisites = new HashSet<Prerequisite>();
            this.Concentrations = new HashSet<Concentration>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public int CourseNumber { get; set; }
        public int CreditHours { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Prerequisite> Prerequisites { get; set; }
        public virtual ICollection<Concentration> Concentrations { get; set; }
    }
}
