//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPSAdvisingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int ID { get; set; }
        public string Semester { get; set; }
        public Nullable<int> Grade { get; set; }
        public bool Selected { get; set; }
        public int BaseCourseID { get; set; }
        public Nullable<int> Student_ID_Taken { get; set; }
        public Nullable<int> Student_ID_Recommend { get; set; }
    
        public virtual BaseCourse BaseCourse { get; set; }
        public virtual Student Student_Taken { get; set; }
        public virtual Student Student_Recommend { get; set; }
    }
}
