//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPSAdvisingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prerequisite
    {
        public int ID { get; set; }
        public string PrereqName { get; set; }
        public Nullable<int> BaseCourse_PreReqIsFor_ID { get; set; }
    
        public virtual BaseCourse BaseCourse_PreReqIsFor { get; set; }
    }
}
