//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPSAdvisingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.CoursesTaken = new HashSet<Course>();
            this.CoursesRecommended = new HashSet<Course>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string WNumber { get; set; }
        public int HoursCompleted { get; set; }
        public double GPA { get; set; }
        public Nullable<int> StudentConcentration_ID { get; set; }
    
        public virtual Concentration Concentration { get; set; }
        public virtual ICollection<Course> CoursesTaken { get; set; }
        public virtual ICollection<Course> CoursesRecommended { get; set; }
    }
}
